language: crystal

crystal:
  - latest
  - nightly

matrix:
  allow_failures:
    - crystal: nightly

addons:
  apt:
    packages:
      - libgphoto2-6
      - libgphoto2-dev
      - libgphoto2-port12

install:
  - shards install

script:
  - crystal spec
  - crystal tool format --check
  - bin/ameba
